config/routes.rb
JobTracker::Application.routes.draw do
  resources :users
  resources :sessions
  resources :jobs do
    resources :job_sessions
  end
  
  get "welcome/index"

  root 'welcome#index'

  get '/auth/:provider/callback', to: 'sessions#create'

  post '/createNewRepo', to: 'jobs#createRepo'

  post '/endSession', to: 'job_sessions#update'

end

app/models/job.rb
class Job < ActiveRecord::Base
	has_many :users, 
		through: :jobs_users
	has_many :jobs_users,
		inverse_of: :job

	has_many :job_sessions, as: :sessionable, dependent: :destroy, autosave: false
	accepts_nested_attributes_for :job_sessions

	validates_format_of :github_repo, with: URI.regexp
	validates_presence_of :github_repo, :title
	validates_uniqueness_of :github_repo
end

app/models/job_session.rb
class JobSession < ActiveRecord::Base
	# belongs_to :job
	belongs_to :sessionable, polymorphic: true
	validates_presence_of :session_title
	validates_presence_of :sessionable_id
	validates_presence_of :sessionable_type
	validates_numericality_of :sessionable_id


	def humanize
	    [[60, :seconds], [60, :minutes], [24, :hours], [1000, :days]].map{ |count, name|
	        if self.length > 0
	            self.length, n = self.length.divmod(count)
	            "#{n.to_i} #{name}"
		    end
		}.compact.reverse.join(' ')
	end
end

app/models/jobs_user.rb
class JobsUser < ActiveRecord::Base
	belongs_to :job
	belongs_to :user
end

app/models/jobs_users.rb
class JobsUsers < ActiveRecord::Base
	belongs_to :job
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :jobs, 
		through: :jobs_users
	has_many :jobs_users,
		inverse_of: :user

	# has_many :job_sessions, as: :sessionable
	validates_presence_of :github_uid, :name, :email
	validates_uniqueness_of :github_uid, :display_name

	def self.find_for_github_oauth(uid, name, email, nickname)
	    user = User.where(github_uid: uid).first

	    if user
	        return user
	    else
	    	registered_user = User.where(:email => email).first
	    	if registered_user
	        	return registered_user
	    	else
	        	user = User.create(:name => name, :github_uid => uid, :email => email, :display_name => nickname)
	    	end
	    end
        user
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :null_session

      # rescue_from Octokit::UnprocessableEntity, :with => :error_created

	def current_user?
        user = User.where(github_uid: session[:uid]).first
        return user
    end

private
	  def error_created(error)
	    return error.message
	  end 

end

app/controllers/job_sessions_controller.rb
class JobSessionsController < ApplicationController

	def index
	end

	def create
		@job = Job.where(id: params[:job_id]).first
		@job_session = @job.job_sessions.build(job_session_params)
		@job_session.active = true

		if @job_session.save
			# redirect_to :back, notice: "Your work session has begun."
			gon.job_id = @job.id
		    respond_to do |format|
		    	format.html { redirect_to job_url(@job), notice: "Your work session has begun."}
		        # format.json { render json:  @job }
	 	    end
		else
			redirect_to :back, notice: "There was an error starting your session. Please try again. "
		end
	end

	def update
		@job_session = JobSession.find(params[:job_sessionId])
		@job_session.length = params[:length]
		@job_session.active = false
		@job_session.save!
	    respond_to do |format|
	    	# Calls model method humanize to make session length readable, sends it back in json hash
	        format.json  { render json:  {  session: @job_session,
	        								human_length: @job_session.humanize} }
	    end
	end

private
    def job_session_params
        params.require(:job_session).permit( :session_title, :session_goals, :sessionable_id, :sessionable_type)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	respond_to :html, :json

	def index
	end

	def createRepo
		client = Octokit::Client.new(:access_token => session[:token])
	    client.create_repository(params[:repoName])
		@job = Job.new
		@job.github_repo = 'https://github.com/'+current_user?.display_name+'/'+params[:repoName]
	    respond_to do |format|
	        format.json  { render json:  @job }
	    end
    rescue Octokit::UnprocessableEntity
    	@job = Job.new
	    flash[:notice] = "Repository Name is already taken. Please choose another"
	    render action: 'new'
	end

	def new
		@job = Job.new
	end

	def show
		@job = Job.find(params[:id])
		respond_with @job
	end

	def create
		@job = Job.new(job_params)
		@job.users << current_user?
		if @job.save
			redirect_to @job, notice: "Job Created!"
		else
			render action: 'new', notice: "There was an error, Try again."
		end
	end

private
    def job_params
        params.require(:job).permit( :description, :title, :github_repo)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
require "uri"
require "net/http"	
require 'pry'

	respond_to :html, :json


	def create
		@auth = request.env["omniauth.auth"]
	    @token = @auth["credentials"]["token"]
	    session[:uid] = @auth.uid	
	    session[:token] = @token
	    @code = params[:code] 
		
		create_github_user
 	end

	def destroy
	    [:uid, :token].each do |key|
	      session[key] = nil
	    end
	    # binding.pry
	    redirect_to root_path
	    flash[:notice] = "You are now logged out."
	end

	def create_github_user
		@user = User.find_for_github_oauth(@auth.uid, @auth.info.name, @auth.info.email, @auth.info.nickname)

	    if @user.persisted? 
	      redirect_to root_path, notice: 'You have successfully signed in!'
	    else
	      redirect_to root_path
	      flash[:notice] = "There was a problem signing you in. Please try again."
	    end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user?
    user = User.where(github_uid: session[:uid]).first
    return user
  end

 #  def include_gon
	#   data = Rails.cache.read('gon_variables') || {}

	#   script = "<script>window.gon = {};"
	#   data.each do |key, val|
	#     script += "gon." + key.to_s + val.to_json + ";"
	#   end
	#   script += "</script>"
	#   script.html_safe
	# end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/jobs/_users_jobs.html.erb
<%- current_user?.jobs.each do |job| -%>
	<div class="small-12 columns">
		<%=link_to job.title, job_path(job) %>
	</div>
	<div class="small-12 columns">
		<%= job.description %>
	</div>
	<div class="small-12 columns">
		<%= job.github_repo %>
	</div>
	<div class="small-12 columns">
		<%= job.created_at %>
	</div>
<%- end -%>	

app/views/jobs/index.html.erb
<h4> Index page </h4>

app/views/jobs/new.html.erb
<%= simple_form_for @job do |f| %>
	
	<h4>Start a new Job</h4>
    <%= f.input :title %>
	<%= f.input :github_repo %>
  	<button type=button class="new_repo_btn">Create the Repo Now</button>
    <%= f.input :description, as: :text, required: false %>
    <%= f.button :submit %>

<% end %>
<% content_for :javascript do %>
    <script>
    </script>
<% end %>

app/views/jobs/show.html.erb
<div class="row">
	<div class="small-12 large-6 columns">
		<h1> Job page</h1>
		<h3><%= @job.title %></h3>
		<div>Github Repository:<%= @job.github_repo %></div>
		<div>Description:<%= @job.description %></div>
		<h3>Start a new sessions</h3>
		<div><%= link_to 'Start a new job session' %></div>

		<div>
			<%= simple_form_for [@job, @job.job_sessions.build] do |f| %>
				<%= f.input :session_title %>
				<%= f.input :session_goals, as: :text %>
				<%= f.submit 'Create Session'%>
			<% end %>
		</div>
	</div>

	<div class="small-12 large-6 columns">
		<!-- Should eventually show all job sessions. Only showing most recent -->
		<h3> Current Session</h3>
		<%- job_sessions = @job.job_sessions -%>
		<%- current_session = @job.job_sessions.reverse[1] -%>
		<%- if (current_session != []) && (current_session != nil  && (current_session.active?))-%>
			<h4>Session title</h4>
			<%= current_session.session_title %>
			<h4>Session Goals</h4>
			<%= current_session.session_goals %>
			<h4>Session Length</h4>
			<div id="current_session_length"><%= current_session.length %></div>

			<%- if current_session.active? -%>
				<div class="stopwatch" data-timer="0" style="width: 400px;">
				</div>
				<div>
					<button type=button class="timer_start">Start Timer</button>
					<button type=button class="timer_stop">Pause Session</button>
					<button type=button class="session_end">End Session</button>
				</div>
				<%- end -%>
		<%- end -%>
	</div>
	<div class="small-12 columns">
		<%- job_sessions.reverse.each do |session| -%>
			<%- if (session.id != nil) && (!session.active?) -%>
				<div class="small-12 columns" style="border: 2px solid grey;">
					<p>Session title: <%= session.session_title %></p>
					<p>Session Goals: <%= session.session_goals %></p>
					<p>Session Length: <%= session.humanize %><p>
				</div>
			<%- end -%>
		<%- end -%>
	</div>
</div>

<script>
	<%- if current_session != nil -%>
		window.job_sessionId = <%= @job.job_sessions.reverse[1].id %>;
	<%- end -%>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

        <%= stylesheet_link_tag    "application" %>
        <%= javascript_include_tag "vendor/modernizr" %>
        <%= csrf_meta_tags %>
    </head>

    <body>

        <% if current_user? %>
            <%= link_to 'Sign Out', session_path("delete"), method: :delete%>
        <% else %>
            <div><%= link_to 'Sign in', '/auth/github' %></div>
        <% end %>


        <%- if notice !=  nil -%>
            <div data-alert class="alert-box alert row ">
                <p class="small-6 large-centered columns"><%= notice %></p>
            </div>
        <%- end -%>
      
        <%= yield %>

        <%= javascript_include_tag 'jquery', "application" %>
        <%= yield :javascript %>

    </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome. TrackIT</h1>

<div class="row">
	<% if current_user? %>
		<div class="small-12 columns">
			<%= link_to 'Start a new Job', new_job_path %>
		</div>
		<%= render 'jobs/users_jobs' %>
	<% end %>
</div>